version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: org.springframework.boot
    versions:
    - 2.5.0-M1
    - 2.5.0-M2
    - 2.5.0-M3
